---
- hosts: master
  remote_user: vagrant
  become: yes
  become_method: sudo
  tasks:
      - name: Add and enable the kubernetes repo
        yum_repository:
          name: kubernetes
          description: Kubernetes repository
          baseurl: http://yum.kubernetes.io/repos/kubernetes-el7-x86_64
          enabled: yes
          gpgcheck: no
          repo_gpgcheck: no
          # gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

        # no longer be necessary on CentOS once #33555 is included in a released version of kubeadm.
      - name: disabled selinux
        selinux: state=disabled
      - name: Install required packages
        yum: pkg=docker,kubelet,kubeadm,kubectl,kubernetes-cni state=present
      - name: enable and start Docker
        service: name=docker state=started enabled=yes
      - name: enable and start kublet
        service: name=kubelet state=started enabled=yes

- hosts: minions
  remote_user: vagrant
  become: yes
  become_method: sudo
  tasks:
      - name: Add and enable the kubernetes repo
        yum_repository:
          name: kubernetes
          description: Kubernetes repository
          baseurl: http://yum.kubernetes.io/repos/kubernetes-el7-x86_64
          enabled: yes
          gpgcheck: no
          repo_gpgcheck: no
          # gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

        # no longer be necessary on CentOS once #33555 is included in a released version of kubeadm.
      - name: disabled selinux
        selinux: state=disabled
      - name: Install required packages
        yum: pkg=docker,kubelet,kubeadm,kubectl,kubernetes-cni state=present
      - name: enable and start Docker
        service: name=docker state=started enabled=yes
      - name: enable and start kublet
        service: name=kubelet state=started enabled=yes
